config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }



  resources :users

  resources :products, only: [:index] do
    delete 'orders/:order_id', to: 'products#destroy',  as: 'destroy'
    resource  :orders, only: [:create]
  end

  resources :billings, only: [] do
      collection do
          get 'pre_pay'
          get 'execute'
        end
  end


  get 'orders/:id_order', to: 'orders#pagar',  as: 'pagar'


  resources  'orders', only: :index

  root  'products#index'

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :master_order
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!
# before_action :authenticate_user, only: [:pag1, :pag2]
# before_action :authenticate_user, except: [:pag3, :pag4]
  # before_action :filter_admin!

  def destroy
    byebug
  end
  def pagar
      # master_order = MasterOrder.find(params[:id_order])
      # master_order.status = true
      # master_order.save
      # redirect_to products_path, notice:'Se ha generado la compra, se ha enviado un correo con el detalle'
  end

  def create
    byebug
    if params[:cantidad] == '0' || params[:cantidad] == ''
        redirect_to root_path, alert:'No puede ser cantidad cero'
    else
      master_order = MasterOrder.where(user_id: current_user.id, status: false)
      if master_order.count ==  0
          # Si no tiene ordenes abiertas genero una nueva
          orden = MasterOrder.create(user_id:current_user.id, status: false)
          number_order = orden.id
          master_order = orden
      else
          number_order = master_order.first.id
      end

      @order = Order.new
      @order.product = Product.find(params[:product_id])
      @order.quantity = params[:cantidad]
      @order.master_order_id = number_order
      @order.price = @order.product.price
      @order.user = current_user
      if @order.save
        redirect_to root_path, notice:'Se ha ingresado al carrito de compra'
      else
        redirect_to root_path, alert:'Problema al cargar carrito de compra'
      end
    end
  end

  def index
      carro = current_user.master_orders.where(status: false)
      @total = 0
      @orders = []
      if carro.count > 0
        @orders = carro.take.orders
        @orders.each do  |v|
          @total += ( v.price.to_i * v.quantity.to_i )
        end
      end
  end

# private
#
#     def filter_admin!
#       authenticate_user!
#       redirect_to root_path, alert: "No tienes acceso" unless current_user.isadmin?
#     end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/index.html.erb
<% if !@orders.empty? %>
<h1>Su Número de Solicitud de Compra es: <%= @orders.take.master_order_id %> </h1>

<div class="row">
<% @orders.each do |p| %>
 <div class="col-sm-3">
  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="<%= p.product.photo %>" alt="Card image cap">
    <div class="card-body text-center">
      <h5 class="card-title"><%= p.product.name %></h5>
      <h1 class="card-text text-danger">Cantidad:$<%= p.quantity%></h1>
      <h1 class="card-text text-danger">Precio:$<%= p.price.to_i %></h1>
      <h1 class="card-text text-danger">Total:$<%= p.price.to_i * p.quantity.to_i  %></h1>
      <%= link_to "Eliminar",  product_destroy_path(p.product.id,p.id), method: :delete, class:'btn btn-warning' %>
    </div>
  </div>
  </div>
<% end %>
</div>
<br>
<h1>Total Productos:<%= @total %></h1>
<br>
<%= link_to 'Pagar', pagar_path(@orders.take.master_order_id), class:'btn btn-primary'  %>

<%= link_to 'Pagar PayPal', pre_pay_billings_path, class:'btn btn-primary'  %>


<% end %>