config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }



  resources :users

  resources :products, only: [:index] do
    delete 'orders/:order_id', to: 'products#destroy',  as: 'destroy'
    resource  :orders, only: [:create]
  end

  resources :billings, only: [] do
      collection do
          get 'pre_pay'
          get 'execute'
        end
  end


  get 'orders/:id_order', to: 'orders#pagar',  as: 'pagar'


  resources  'orders', only: :index

  root  'products#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarrgoCompra</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "devise/shared/navbar" %>
    <% if notice.present? %>
    <div class="alert alert-success">
      <strong><%= notice %></strong>
    </div>
    <% end %>
    <% if alert.present? %>
    <div class="alert alert-danger">
      <strong><%= alert %></strong> .
    </div>
    <% end %>

<% if user_signed_in? %>
    <div class="row">
      <%= render "devise/shared/navbar_con" %>
      <div class="col-sm-9">
          <%= yield %>
      </div>
     </div>
<% else %>
  <div class="container">
    <%= yield %>
  </div>
<% end %>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/new.html.erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
  </div>

    <div class="form-group">
      <%= f.label :url, "URL Imagen", class: "control-label" %> <br/>
      <div>
        <%= image_tag(resource.url.thumb, style: "margin-bottom: 10px; border-radius: 5px;") if resource.url? %>
        <%= f.text_field :remote_url_url, id: :history_picture, class: "form-control" %>
      </div>
      <%= f.hidden_field :url_cache %>
    </div>
    <div class="form-group">
        <%= f.label :bio, "Descripción", class: "control-label" %> <br/>
        <%= f.text_area :bio, id: :bio,  rows: 10, cols:80%>
    </div>

    <div class="field">
        <%= f.label :age, "Edad" %> <br/>
        <%= f.text_field :age, id: :age%>
    </div>

    <div class="field">
      <%= f.label :genero, "Gernero" %><br />
      <%= f.email_field :genero, id: :genero%>
    </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>

<% end %>

<%= render "devise/shared/links" %>
</div>